# Generated by Django 5.1 on 2024-08-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Patient'), (1, 'Doctor')], null=True),
        ),
    ]
